### ISSUE TITLE
Can't we unfollow them after we got list?

### ISSUE THREAD

**Issue by princebhalani143** [JimishF/instaUnfollow#1]
Hello,

It's really nice script what I am looking for, Can't we unfollow all of them who's not following back? So, When we have list ready we can unfollow them in same way :)

Thanks,
Prince

**Comment by JimishF** [comment]
We can do that Prince, but the main issue is Instagram blocks and revokes unfollow access for a day if we make too much unfollow requests in such a short time. Same thing happens with facebook too. If we put a script to 'like' all posts on a single enter, it will block you and you will not able to like any posts for a time.
