### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by jonathanfilbert** [JimishF/instaUnfollow#7]
*The console returned something like this:*
TypeError: _x.following_elm is undefined

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://graph.instagram.com/logging_client_events’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).

**Comment by JimishF** [comment]
That console log is from instagram itself and does not have any concern with this script.
