### ISSUE TITLE
Doesn't works!

### ISSUE THREAD

**Issue by dghido** [JimishF/instaUnfollow#8]
`VM693:1 Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined
    at eval (eval at <anonymous> (?hl=it:1), <anonymous>:1:664)
    at <anonymous>:1:10205
(anonymous) @ VM693:1
(anonymous) @ VM692:1`

How can I solve it?

**Comment by JimishF** [comment]
Since Instagram code updates in a while, You'll need to change the selectors in the original script.

**Comment by dghido** [comment]
where can I find the correct selectors?

This selectors are the default.
`selectors = {
    modalTrigger: 'Y8-fY',
    unameElement: 'FPmhX',
    userLi: 'NroHT',
    closeBtn: 'ckWGn',
    flwTitle: 't48Bo',
    objDiv: "j6cq2"
}`

**Comment by JimishF** [comment]
Selectors are class names of dom elements in the Instagram web, which are used for clicking, scrolling, matching etc.

**Comment by JimishF** [comment]
In this case, I think there is no issue with the selectors at all. Either you're not logged in or you are Trying it on someone who's account is private and you're not following them.

**Comment by sidvud98** [comment]
How to find the updated selectors now @JimishF

**Comment by JimishF** [comment]
updating selectors will still throw errors since Instagram added a bunch of  "Suggestions" crap within Modal of followers/following list. I'm working on a totally new script from scratch. Keep it stared to get updates.
