### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by worldsdream** [JimishF/instaUnfollow#9]
I am on my page. I run the code:  index.js
I get a popup with all the users that are following me. I see who I am following and the ones that are following me. But I don't see the people that I am following and they are NOT following me. So I can easily unfriend them.

**Comment by JimishF** [comment]
Yeah, That's because Instagram has updated the design recently. After tracing out, I found that we need to change the selector for close button.

**Comment by worldsdream** [comment]
Will you update the code. So I can test it out. Let me know.

**Comment by JimishF** [comment]
Yes, Its done.
